language: java
jdk:
  - oraclejdk8

script:
  - ./gradlew check
  - ./gradlew install -x check
  - ./gradlew codeCoverageReport --continue

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true
